### ISSUE TITLE
Move CI away from Travis

### ISSUE THREAD

**Issue by nbraud** [ppb/ppb-vector#117]
Since its acquisition, Travis CI fired most of its core engineering team, and the free service has become unbearably slow (dozens of minutes before a job even starts).

Given the impact on development velocity and QA (a couple of PRs were just merged without waiting for CI), and given the apparent lack of future for travis-ci.org, I suggest we move somewhere else.

I seem to recall @astronouth7303 suggesting [Cirrus CI](https://cirrus-ci.org/), which has native support for Linux, macOS, Windows and FreeBSD.  As a plus, having something container-based means we can stop piling up hacks to deal with Travis' environments.

**Comment by astronouth7303** [comment]
On top of the fact that travis was already kinda terrible.
