### ISSUE TITLE
Add reflect method

### ISSUE THREAD

**Issue by pathunstrom** [ppb/ppb-vector#45]
A reflect method would be useful for managing bouncing physics.

Expected usage:

    vector = Vector2(1, 1)
    surface_normal = Vector(-1, 0)
    reflected_vector = vector.reflect(surface_normal)
    assert reflected_vector == Vector(-1, 1)

**Comment by avik-pal** [comment]
I would like to deal with this issue if no one has a problem

**Comment by pathunstrom** [comment]
@avik-pal Thank you for the interest, but I just did the work on this tonight.

Please feel free to submit a PR with potential improvements.

**Comment by pathunstrom** [comment]
Working with #46

**Comment by avik-pal** [comment]
Added a pull request with a few changes to the reflect function

**Comment by pathunstrom** [comment]
The test is good, the code change isn't. Expect a PR if I can resolve it soon.
