### ISSUE TITLE
Round all calculations like in rotate

### ISSUE THREAD

**Issue by pathunstrom** [ppb/ppb-vector#48]
For now, all rounding can happen to 5 digits.

[Line 115](https://github.com/ppb/ppb-vector/blob/master/ppb_vector/vector2.py#L115) looks how it does specifically because of rounding errors. If we clean this up, the code becomes cleaner and slightly easier to manage.

**Comment by astronouth7303** [comment]
I assume she means https://github.com/ppb/ppb-vector/blob/4e5efc0923d31d026c2d9295df597357c8b7318e/ppb_vector/vector2.py#L101-L102

I agree with the underlying problem that floating point can sometimes be too precise and we should probably have tools to make doing fuzzy comparisons easy (and possibly the norm).

However, I'm concerned that simply rounding after every operation will cause inconsistency problems (eg, rotating 36 times by 10 degrees won't come to the starting point).

**Comment by nbraud** [comment]
FWIW, this should be closed now that there is no rounding anymore.

**Comment by nbraud** [comment]
Ping?

**Comment by nbraud** [comment]
@pathunstrom @astronouth7303 Can you close the issue?
