### ISSUE TITLE
Test Vector addition

### ISSUE THREAD

**Issue by pathunstrom** [ppb/ppb-vector#5]
Add tests to test vector addition between 2 `Vector2`s, and `Vector2`s and vector-like objects: tuples, lists, dicts, and other objects that can support indexing or key access.

**Comment by jms** [comment]
i would like to work in this issue.

**Comment by pathunstrom** [comment]
Feel free. We're using pytest with this project, please make sure to test multiple values and each vector like object with the class.

**Comment by jms** [comment]
great, this is my pull request #30
