### ISSUE TITLE
Add property-based testing

### ISSUE THREAD

**Issue by nbraud** [ppb/ppb-vector#59]
I think it would make sense, in many cases, to run tests not against hardcoded inputs (and expected outputs), but against random inputs (and properties/equations that should hold).
For instance, `x.angle(x.rotate(alpha)) ≃ alpha` for any vector `x` and angle `alpha`.

Given that `ppb-vector` is a math library, and written in an effects-free style, it seems to be a great fit for property-based testing, and I can recommend the [Hypothesis](https://hypothesis.works/) property-based testing library.

It would probably make sense to first add some automation to track line- or path-coverage of the testsuite, ideally ran automatically in CI, but this isn't a strong blocker either.

**Comment by astronouth7303** [comment]
It's hard to do useful things with coverage without roping in another service.

Also, #58.

**Comment by nbraud** [comment]
@astronouth7303  I suggested coverage tracking because this would allow removing unit tests that were superseded by property-based tests with confidence, but that doesn't need to be done in CI if you don't mind checking by hand when reviewing a PR that removes a unit test.

**Comment by nbraud** [comment]
This can be closed, as the latest round of PRs should have brought pretty good coverage of the API with property-based tests.
