### ISSUE TITLE
Add CONTRIBUTORS.md

### ISSUE THREAD

**Issue by pathunstrom** [ppb/ppb-vector#6]
Add all users in the commit history.

**Comment by Supun94** [comment]
@pathunstrom I would like to take this issue. Do you have any other important things need to mention in CONTRIBUTING.md ?

**Comment by pathunstrom** [comment]
@Supun94 I typoed this issue: This should be CONTRIBUTORS.md and match the style of the [pursuedpybear](https://github.com/ppb/pursuedpybear)

**Comment by Supun94** [comment]
If so shall I send another PR? IMHO it would be nice to have CONTRIBUTING.md as well :)

**Comment by pathunstrom** [comment]
I agree it'd be nice, but it's going to be a lot more work! There's the one I'm using in the other repo that might need some editing to fit this repo, but you're welcome to work on it!

**Comment by deveshd2k** [comment]
@pathunstrom I would like to take this issue. What extra you want to be added to the CONTRIBUTERS.md file?

**Comment by pathunstrom** [comment]
@deveshd2k There's a CONTRIBUTORS.md in [pursuedpybear](https://github.com/ppb/pursuedpybear) that you can copy the format of.

The maintainers will be the same, then developers we need to add an entry with every person who has committed to this repo. Don't worry about email/twitter profiles, just the github links is fine.

**Comment by deveshd2k** [comment]
Okay.
I will add the information two maintainers and the four contributors of this repository.

**Comment by deveshd2k** [comment]
Submitted the pr #36

**Comment by pathunstrom** [comment]
Closed with #36
