### ISSUE TITLE
Test Vector Subtraction

### ISSUE THREAD

**Issue by pathunstrom** [ppb/ppb-vector#7]
Add tests to test vector subtraction between 2 `Vector2`s, and `Vector2`s and vector-like objects: tuples, lists, dicts, and other objects that can support indexing or key access.

**Comment by BlaineDuBois** [comment]
How would you like me to test the vector subtraction?

**Comment by pathunstrom** [comment]
The project will be using pytest, feel free to make a module specifically for unittesting substraction.

* Test using two `Vector2`s against each other with various values.
* Test using a `Vector2` and a list both as the first operand and the second operand with various values.
* Test using a `Vector2` and a tuple both as the first operand and the second operand with various values.
* Test using `Vector2` and a dictionary  both as the first operand and the second operand with various values.
*  Test using `Vector2` and a vector-like class with an `x` and `y` attribute both as the first operand and the second operand with various values.
