### ISSUE TITLE
Testing parameter names should be improved for readability

### ISSUE THREAD

**Issue by pathunstrom** [ppb/ppb-vector#75]
It took me a bit to realize `l` in https://github.com/ppb/ppb-vector/pull/64 was length, and if I can't read it, newer devs who don't have domain knowledge _definitely_ can't.

Let's avoid single character variable names everywhere we can. Exceptions include `x` and `y` inside much of the code.

**Comment by nbraud** [comment]
You mean in `test_rotation_linearity`?
If so, `l` isn't being used as a length, but as a(n arbitrary) scalar to multiply `a` with.

I've tried to keep my use of letters consistent (i.e. `x`, `y`, ... for vectors, `l` for the scalar in a linearity test, ...), but clearly it's wasn't 100% consistent (that test uses `a` and `b` for vectors).
